baseline_speed = 1.0
no_boids = 1024
sample_rate = 16
save = true
save_timestamp = true 
save_path = "./"
dbscan_flock_clustering_on = true
init_width = 1000
init_height = 1000
sensory_distance = 40.0
alignment_coefficient = 0.1
cohesion_coefficient = 0.06
separation_coefficient = 0.3
alignment_treshold_coefficient = 1
cohesion_treshold_coefficient = 0.8
separation_treshold_coefficient = 0.3
min_speed = 2.1
max_speed = 2.1
max_steering = 0.65
field_of_vision = 280.0
wander_on = false
wander_rate = 0.4
wander_radius = 11.5
wander_random = true
wander_distance = 13
wander_coefficient = 1.0
size = 5.0
rules_impl = false
agent_steering = false