baseline_speed = 1.0
no_boids = 1024
sample_rate = 16
save = true
save_timestamp = true 
save_path = "./"
dbscan_flock_clustering_on = true
init_width = 1000
init_height = 1000
sensory_distance = 40.0
alignment_coefficient = 0.2
cohesion_coefficient = 0.1
separation_coefficient = 2.5
alignment_treshold_coefficient = 1
cohesion_treshold_coefficient = 0.8
separation_treshold_coefficient = 0.3
min_speed = 2
max_speed = 2
max_steering = 0.3
field_of_vision = 280.0
wander_on = false
wander_rate = 0.2
wander_radius = 5.2
wander_random = false
wander_distance = 21.5
wander_coefficient = 0.14
size = 5.0
rules_impl = false
agent_steering = true