baseline_speed = 1.0
no_boids = 4096
sample_rate = 8
save = true
save_timestamp = true 
save_path = "./"
dbscan_flock_clustering_on = true
init_width = 500
init_height = 500
sensory_distance = 10.0
alignment_coefficient = 0.3
cohesion_coefficient = 0.3
separation_coefficient = 4.1
alignment_treshold_coefficient = 1.15
cohesion_treshold_coefficient = 0.95
separation_treshold_coefficient = 0.3
min_speed = 2.0
max_speed = 2.0
max_steering = 0.45
field_of_vision = 230.0
wander_on = true
wander_rate = 0.375
wander_radius = 11.5
wander_distance = 13
wander_coefficient = 0.2
size = 1.5