no_boids = 4096
sample_rate = 4
save = true
save_timestamp = false
init_width = 1500
init_height = 900
sensory_distance = 10.0
allignment_coefficient = 0.3
cohesion_coefficient = 0.3
separation_coefficient = 4.1
allignment_treshold_coefficient = 1.15
cohesion_treshold_coefficient = 0.95
separation_treshold_coefficient = 0.3
min_speed = 2.0
max_speed = 2.0
max_steering = 0.45
field_of_vision = 230.0
wander_on = true
wander_rate = 0.35
wander_radius = 11.5
wander_distance = 13
wander_coefficient = 0.2
size = 1.5