baseline_speed = 1.0
no_boids = 8192
sample_rate = 4
save = true
save_timestamp = false
init_width = 1500
init_height = 900
sensory_distance = 60.0
alignment_coefficient = 0.02
cohesion_coefficient = 0.002
separation_coefficient = 4.1
alignment_treshold_coefficient = 1.15
cohesion_treshold_coefficient = 0.95
separation_treshold_coefficient = 0.3
min_speed = 0.5 
max_speed = 2.0
max_steering = 0.6
field_of_vision = 200.0
agent_steering = true