baseline_speed = 1.0
no_boids = 256
sample_rate = 4
save = true
save_timestamp = false
init_width = 1600
init_height = 1600
sensory_distance = 50.0
alignment_coefficient = 0.02
cohesion_coefficient = 0.002
separation_coefficient = 4.1
alignment_treshold_coefficient = 1.15
cohesion_treshold_coefficient = 0.95
separation_treshold_coefficient = 0.35
min_speed = 2.0
max_speed = 2.0
max_steering = 0.65
field_of_vision = 200.0
agent_steering = true