baseline_speed = 1.0
no_boids = 8192 
sample_rate = 32
save = false
save_timestamp = false
init_width = 1500
init_height = 900
sensory_distance = 11.0
allignment_coefficient = 0.2
cohesion_coefficient = 0.08
separation_coefficient = 5
allignment_treshold_coefficient = 0.86
cohesion_treshold_coefficient = 1.22
separation_treshold_coefficient = 0.4
min_speed = 2.35
max_speed = 2.35
max_steering = 0.65
field_of_vision = 360.0
wander_on = false
size = 3.0