baseline_speed = 1.0
no_boids = 1024
sample_rate = 4
save = true 
save_timestamp = false
init_width = 1000
init_height = 1000
sensory_distance = 15.0
allignment_coefficient = 0.1
cohesion_coefficient = 0.05
separation_coefficient = 0.5
allignment_treshold_coefficient = 1.0
cohesion_treshold_coefficient = 1.0
separation_treshold_coefficient = 0.5
min_speed = 2.0
max_speed = 2.0
max_steering = 0.9
field_of_vision = 220.0
wander_on = false
wander_rate = 0.4
wander_radius = 5.2
wander_distance = 15.0
wander_coefficient = 0.18
size = 3
rules_impl = false