baseline_speed = 1.0
no_boids = 8192 
sample_rate = 32
save = false
save_timestamp = false
init_width = 1500
init_height = 900
sensory_distance = 11.0
allignment_coefficient = 0.2 
cohesion_coefficient = 0.3
separation_coefficient = 3.1
allignment_treshold_coefficient = 1.15
cohesion_treshold_coefficient = 0.95
separation_treshold_coefficient = 0.25
min_speed = 0.65
max_speed = 2.35
max_steering = 0.65
field_of_vision = 210.0
wander_on = true
wander_rate = 0.375
wander_radius = 11.5
wander_distance = 0.5
wander_coefficient = 0.21
size = 3.0