baseline_speed = 1.0
no_boids = 1024 
sample_rate = 32
save = false
save_timestamp = false
init_width = 1500
init_height = 900
sensory_distance = 25.0
allignment_coefficient = 0.2
cohesion_coefficient = 0.3
separation_coefficient = 4.1
allignment_treshold_coefficient = 1.15
cohesion_treshold_coefficient = 0.95
separation_treshold_coefficient = 0.35
min_speed = 2.0
max_speed = 2.0
max_steering = 0.65
field_of_vision = 240.0
wander_on = true
wander_rate = 0.375
wander_radius = 11.5
wander_distance = 0.5
wander_coefficient = 0.10
size = 3
rules_impl = true