no_boids: 256
sample_rate: 4
save: true
save_timestamp: false
init_width: 800.0
init_height: 600.0
sensory_distance: 60.0
allignment_coefficient: 0.004
cohesion_coefficient: 0.2
separation_coefficient: 10.0
allignment_treshold_coefficient: 1.15
cohesion_treshold_coefficient: 0.95
separation_treshold_coefficient: 0.48
min_speed: 0.65
max_speed: 2.2
max_steering: 0.9
field_of_vision_deg: 200.0