no_boids = 512 
sample_rate = 8
save = true
save_timestamp = false
init_width = 1500
init_height = 900
sensory_distance = 60.0
allignment_coefficient = 0.004
cohesion_coefficient = 0.2
separation_coefficient = 10.0
allignment_treshold_coefficient = 1.15
cohesion_treshold_coefficient = 0.95
separation_treshold_coefficient = 0.48
min_speed = 2
max_speed = 2
max_steering = 0.9
field_of_vision = 200.0
wander_on = true
wander_rate = 0.7
wander_radius = 5.2
wander_distance = 21.5
wander_coefficient = 0.3
size = 1.5