baseline_speed = 1.0
no_boids = 512 
sample_rate = 4
save = true
save_timestamp = false
init_width = 1500
init_height = 900
sensory_distance = 60.0
alignment_coefficient = 0.000
cohesion_coefficient = 0.2
separation_coefficient = 10.0
alignment_treshold_coefficient = 1.15
cohesion_treshold_coefficient = 0.95
separation_treshold_coefficient = 0.48
min_speed = 0.65
max_speed = 2.2
max_steering = 0.6
field_of_vision = 200.0