baseline_speed = 0.10
no_boids = 1000
sample_rate = 2
save = true
save_timestamp = true 
save_path = "./"
dbscan_flock_clustering_on = false
init_width = 1000
init_height = 1000
sensory_distance = 10.0
alignment_coefficient = 1
cohesion_coefficient = 0
separation_coefficient = 0
alignment_treshold_coefficient = 1
cohesion_treshold_coefficient = 1
separation_treshold_coefficient = 1
min_speed = 3.0
max_speed = 3.0
max_steering = 1
field_of_vision = 360.0
wander_on = false
wander_rate = 0.75
wander_radius = 11.5
wander_distance = 13
wander_coefficient = 0.2
size = 1.5