---
output: html_document
---

Load libraries, install boidr
```{r error=FALSE, warning=FALSE, message=FALSE, results='hide'}
library(tidyr)
library(dplyr)
library(ggplot2)
library(rextendr)
setwd("~/Source/Repos/boids_rust/boidr")
rextendr::document()
devtools::load_all(".")

# data_folder <- "~/Source/Repos/boids_rust/boidranalysis/Data/"
data_folder <- "./Data/"
```

get flocking data
```{r}
boid_data <- flock_return(no_iter = 8000, init_boids = 256, save_locations_path = data_folder, sample_rate = 8, init_width = 4000, init_height = 4000)
boid_data2 <- flock_detailed(no_iter = 8000, 
                             init_boids = 512,
                             save_locations_path = data_folder,
                             sample_rate = 8,
                             init_width = 4000, 
                             init_height = 4000, 
                             sensory_distance = 50,
                             allignment_coef = .02,
                             allignment_trs_coef = 1.15,
                             cohesion_coef = 0.002, 
                             cohesion_trs_coef = .95,
                             separation_coef = 4.1,
                             separation_trs_coef = .3,
                             min_speed = .5,
                             max_speed = 2.,
                             max_steering = .65,
                             dbscan_clustering = T)
```
visualise
```{r}
direction_data_by_boid <- boid_data %>%
  group_by(id) %>%
  summarise(
    headings = get_headings(x, y)
  ) %>%
  summarise(
    bearings = get_bearings(headings),
    headings = headings[2:length(headings)]
  ) %>%
  ungroup(id)

print("range of bearings:")
range(direction_data_by_boid$bearings)

print("range of headings:")
range(direction_data_by_boid$headings)

headings_binned <- direction_data_by_boid %>%
  mutate(
    headings = round(headings, 0)
  ) %>%
  group_by(headings) %>%
  summarise(
    count = length(id)
  ) %>%
  select(heading = headings, count = count)

bearings_binned <- direction_data_by_boid %>%
  mutate(
    bearings = round(bearings, 0)
  ) %>%
  group_by(bearings) %>%
  summarise(
    count = length(id)
  ) %>%
  select(bearing = bearings, count = count)

ggplot(headings_binned, aes(x = heading, y = log10(count))) +
  coord_polar(theta = "x", start = pi) +
  geom_bar(stat = "identity", fill = "deeppink4", width = .9) +
  # geom_hline(yintercept = seq(0, 500, by = 100), color = "grey80", size = 0.3) +
  # scale_x_continuous(breaks = 0:24, expand = c(.002,0)) +
  labs(x = "Heading w.r.t N") +
  theme_bw()

summary(direction_data_by_boid %>% select(-id))

```
```{r}

ggplot(bearings_binned, aes(x = bearing, y = log10(count))) +
  coord_polar(theta = "x", start = pi) +
  geom_bar(stat = "identity", fill = "deeppink4", width = .9) +
  # geom_hline(yintercept = seq(0, 500, by = 100), color = "grey80", size = 0.3) +
  # scale_x_continuous(breaks = 0:24, expand = c(.002,0)) +
  labs(x = "Heading w.r.t N") +
  theme_bw()
```
```{r}
ggplot(direction_data_by_boid, aes(x=headings)) +
    # coord_polar(theta = "x", start = pi) +
geom_density(color="aquamarine4", fill="aquamarine3") +
  theme_bw()

```
```{r}
ggplot(direction_data_by_boid, aes(x=bearings)) +
  geom_density(color="aquamarine4", fill="aquamarine3") +
  # coord_polar(theta = "x", start = pi) +
  # scale_x_continuous(
  #   breaks = seq(0, 359, 45),
  #   minor_breaks = seq(0, 359, 15)
  # )
  theme_bw()
```


```{r}

ggplot(headings_binned) +
  geom_col(aes(x = heading, y = log(count))) +
  scale_x_continuous(
    breaks = seq(-180, 179, 45),
    minor_breaks = seq(-180, 179, 15)
  ) +
  coord_polar() +
  theme_bw()
```

