[package]
name = "boids_app"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = [ "derive" ]}
serde = "1"
nannou = "0.19"
nannou_egui = "0.19"
boids_lib = { path = "../boids_lib" }
csv = "1.3"
clap-serde-derive = "0.2"
serde_yaml = "0.9"
toml = "0.8"
splines = { version = "=4.2.0", features = [ "glam"]}
itertools = "0.13"
circular-queue = "0.2"
