[package]
name = 'boidr'
version = '0.1.0'
edition = '2018'
resolver = "2"

[lib]
crate-type = [ 'staticlib' ]

[dependencies]
extendr-api = '*'
boids_lib = { path = "/Users/filipvlcek/Source/Repos/boids_rust/boids_lib"}
geo = "0.23.1"
# boids_test_lib = { path = "./../../../boids_test_lib"}